// Code generated by internal/api/stubgen. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

// ErrNotImplemented is returned by every Unimplemented method; the server maps it to 501 not_implemented.
var ErrNotImplemented = errors.New("not implemented")

// Unimplemented answers every operation with ErrNotImplemented. Embed it and define the operations you implement.
type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}

func (Unimplemented) AcceptDutchPrice(context.Context, AcceptDutchPriceRequestObject) (AcceptDutchPriceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnAdminAlert(context.Context, ActOnAdminAlertRequestObject) (ActOnAdminAlertResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnAdminAuction(context.Context, ActOnAdminAuctionRequestObject) (ActOnAdminAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnAdminDispute(context.Context, ActOnAdminDisputeRequestObject) (ActOnAdminDisputeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnAdminMarket(context.Context, ActOnAdminMarketRequestObject) (ActOnAdminMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnAdminUser(context.Context, ActOnAdminUserRequestObject) (ActOnAdminUserResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnMatch(context.Context, ActOnMatchRequestObject) (ActOnMatchResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnMmDispute(context.Context, ActOnMmDisputeRequestObject) (ActOnMmDisputeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnMmParticipant(context.Context, ActOnMmParticipantRequestObject) (ActOnMmParticipantResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnOrgProcurement(context.Context, ActOnOrgProcurementRequestObject) (ActOnOrgProcurementResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnOrgSupplier(context.Context, ActOnOrgSupplierRequestObject) (ActOnOrgSupplierResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnOrgTransaction(context.Context, ActOnOrgTransactionRequestObject) (ActOnOrgTransactionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ActOnQuote(context.Context, ActOnQuoteRequestObject) (ActOnQuoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AddOrgInventoryItem(context.Context, AddOrgInventoryItemRequestObject) (AddOrgInventoryItemResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AddOrgSupplySchedule(context.Context, AddOrgSupplyScheduleRequestObject) (AddOrgSupplyScheduleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AnswerInvitation(context.Context, AnswerInvitationRequestObject) (AnswerInvitationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AppealSuspension(context.Context, AppealSuspensionRequestObject) (AppealSuspensionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ApplyContractAction(context.Context, ApplyContractActionRequestObject) (ApplyContractActionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ApplyMarketMaker(context.Context, ApplyMarketMakerRequestObject) (ApplyMarketMakerResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ApplyMyTransactionAction(context.Context, ApplyMyTransactionActionRequestObject) (ApplyMyTransactionActionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ArchiveMyListing(context.Context, ArchiveMyListingRequestObject) (ArchiveMyListingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AwardAuction(context.Context, AwardAuctionRequestObject) (AwardAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) AwardOrgAuction(context.Context, AwardOrgAuctionRequestObject) (AwardOrgAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CloseRfq(context.Context, CloseRfqRequestObject) (CloseRfqResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CompleteOnboarding(context.Context, CompleteOnboardingRequestObject) (CompleteOnboardingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateBuyerAuction(context.Context, CreateBuyerAuctionRequestObject) (CreateBuyerAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateContract(context.Context, CreateContractRequestObject) (CreateContractResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateDirectMarketOrder(context.Context, CreateDirectMarketOrderRequestObject) (CreateDirectMarketOrderResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateMmMarket(context.Context, CreateMmMarketRequestObject) (CreateMmMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateMyListing(context.Context, CreateMyListingRequestObject) (CreateMyListingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateMyWithdrawal(context.Context, CreateMyWithdrawalRequestObject) (CreateMyWithdrawalResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateOrgAuction(context.Context, CreateOrgAuctionRequestObject) (CreateOrgAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateOrgPool(context.Context, CreateOrgPoolRequestObject) (CreateOrgPoolResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateOrgProcurement(context.Context, CreateOrgProcurementRequestObject) (CreateOrgProcurementResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateOrganization(context.Context, CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateRfq(context.Context, CreateRfqRequestObject) (CreateRfqResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateUpload(context.Context, CreateUploadRequestObject) (CreateUploadResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DecideAdminVerification(context.Context, DecideAdminVerificationRequestObject) (DecideAdminVerificationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DecideMmApplication(context.Context, DecideMmApplicationRequestObject) (DecideMmApplicationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DecideOrgAuction(context.Context, DecideOrgAuctionRequestObject) (DecideOrgAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) FollowOpportunity(context.Context, FollowOpportunityRequestObject) (FollowOpportunityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ForgotPassword(context.Context, ForgotPasswordRequestObject) (ForgotPasswordResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) FormMmPoolMarket(context.Context, FormMmPoolMarketRequestObject) (FormMmPoolMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminAlert(context.Context, GetAdminAlertRequestObject) (GetAdminAlertResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminAuction(context.Context, GetAdminAuctionRequestObject) (GetAdminAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminDispute(context.Context, GetAdminDisputeRequestObject) (GetAdminDisputeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminMarket(context.Context, GetAdminMarketRequestObject) (GetAdminMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminOverview(context.Context, GetAdminOverviewRequestObject) (GetAdminOverviewResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminUser(context.Context, GetAdminUserRequestObject) (GetAdminUserResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAdminVerification(context.Context, GetAdminVerificationRequestObject) (GetAdminVerificationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAuction(context.Context, GetAuctionRequestObject) (GetAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetAuctionEvaluation(context.Context, GetAuctionEvaluationRequestObject) (GetAuctionEvaluationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetBusinessProfile(context.Context, GetBusinessProfileRequestObject) (GetBusinessProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetContract(context.Context, GetContractRequestObject) (GetContractResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetConversation(context.Context, GetConversationRequestObject) (GetConversationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetCurrentUser(context.Context, GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetExplorerOverview(context.Context, GetExplorerOverviewRequestObject) (GetExplorerOverviewResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMarket(context.Context, GetMarketRequestObject) (GetMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMmAnalytics(context.Context, GetMmAnalyticsRequestObject) (GetMmAnalyticsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMmMarket(context.Context, GetMmMarketRequestObject) (GetMmMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMmOverview(context.Context, GetMmOverviewRequestObject) (GetMmOverviewResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMmRoundSettlement(context.Context, GetMmRoundSettlementRequestObject) (GetMmRoundSettlementResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyAuctionState(context.Context, GetMyAuctionStateRequestObject) (GetMyAuctionStateResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyDashboard(context.Context, GetMyDashboardRequestObject) (GetMyDashboardResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyFinance(context.Context, GetMyFinanceRequestObject) (GetMyFinanceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyIdentity(context.Context, GetMyIdentityRequestObject) (GetMyIdentityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyKyc(context.Context, GetMyKycRequestObject) (GetMyKycResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyListing(context.Context, GetMyListingRequestObject) (GetMyListingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyMmApplication(context.Context, GetMyMmApplicationRequestObject) (GetMyMmApplicationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyNotificationPrefs(context.Context, GetMyNotificationPrefsRequestObject) (GetMyNotificationPrefsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyReputation(context.Context, GetMyReputationRequestObject) (GetMyReputationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMyTransaction(context.Context, GetMyTransactionRequestObject) (GetMyTransactionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOpportunity(context.Context, GetOpportunityRequestObject) (GetOpportunityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgAnalytics(context.Context, GetOrgAnalyticsRequestObject) (GetOrgAnalyticsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgAuctionEvaluation(context.Context, GetOrgAuctionEvaluationRequestObject) (GetOrgAuctionEvaluationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgInventory(context.Context, GetOrgInventoryRequestObject) (GetOrgInventoryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgOverview(context.Context, GetOrgOverviewRequestObject) (GetOrgOverviewResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgProcurement(context.Context, GetOrgProcurementRequestObject) (GetOrgProcurementResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgSettings(context.Context, GetOrgSettingsRequestObject) (GetOrgSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgSupplier(context.Context, GetOrgSupplierRequestObject) (GetOrgSupplierResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgTeam(context.Context, GetOrgTeamRequestObject) (GetOrgTeamResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOrgTransaction(context.Context, GetOrgTransactionRequestObject) (GetOrgTransactionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetPersonProfile(context.Context, GetPersonProfileRequestObject) (GetPersonProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetPriceSuggestion(context.Context, GetPriceSuggestionRequestObject) (GetPriceSuggestionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetPublicStats(context.Context, GetPublicStatsRequestObject) (GetPublicStatsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetRfq(context.Context, GetRfqRequestObject) (GetRfqResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ImportOrgInventory(context.Context, ImportOrgInventoryRequestObject) (ImportOrgInventoryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) InviteOrgMember(context.Context, InviteOrgMemberRequestObject) (InviteOrgMemberResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) IssueOrgPurchaseOrder(context.Context, IssueOrgPurchaseOrderRequestObject) (IssueOrgPurchaseOrderResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) JoinMarket(context.Context, JoinMarketRequestObject) (JoinMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) JoinOpportunity(context.Context, JoinOpportunityRequestObject) (JoinOpportunityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) JoinOrgPool(context.Context, JoinOrgPoolRequestObject) (JoinOrgPoolResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) LeaveMarket(context.Context, LeaveMarketRequestObject) (LeaveMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) LeaveOpportunity(context.Context, LeaveOpportunityRequestObject) (LeaveOpportunityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) LeaveOrgPool(context.Context, LeaveOrgPoolRequestObject) (LeaveOrgPoolResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminAlerts(context.Context, ListAdminAlertsRequestObject) (ListAdminAlertsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminAuctions(context.Context, ListAdminAuctionsRequestObject) (ListAdminAuctionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminAudit(context.Context, ListAdminAuditRequestObject) (ListAdminAuditResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminDisputes(context.Context, ListAdminDisputesRequestObject) (ListAdminDisputesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminMarkets(context.Context, ListAdminMarketsRequestObject) (ListAdminMarketsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminUsers(context.Context, ListAdminUsersRequestObject) (ListAdminUsersResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAdminVerifications(context.Context, ListAdminVerificationsRequestObject) (ListAdminVerificationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListAuctions(context.Context, ListAuctionsRequestObject) (ListAuctionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListConversations(context.Context, ListConversationsRequestObject) (ListConversationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListExplorerAggregates(context.Context, ListExplorerAggregatesRequestObject) (ListExplorerAggregatesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMarkets(context.Context, ListMarketsRequestObject) (ListMarketsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMmApplications(context.Context, ListMmApplicationsRequestObject) (ListMmApplicationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMmMarketAudit(context.Context, ListMmMarketAuditRequestObject) (ListMmMarketAuditResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMmPipeline(context.Context, ListMmPipelineRequestObject) (ListMmPipelineResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMmPools(context.Context, ListMmPoolsRequestObject) (ListMmPoolsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyAuctions(context.Context, ListMyAuctionsRequestObject) (ListMyAuctionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyContracts(context.Context, ListMyContractsRequestObject) (ListMyContractsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyInvitations(context.Context, ListMyInvitationsRequestObject) (ListMyInvitationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyListings(context.Context, ListMyListingsRequestObject) (ListMyListingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyMarkets(context.Context, ListMyMarketsRequestObject) (ListMyMarketsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyMatches(context.Context, ListMyMatchesRequestObject) (ListMyMatchesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyNotifications(context.Context, ListMyNotificationsRequestObject) (ListMyNotificationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyOpportunities(context.Context, ListMyOpportunitiesRequestObject) (ListMyOpportunitiesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListMyTransactions(context.Context, ListMyTransactionsRequestObject) (ListMyTransactionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOpportunities(context.Context, ListOpportunitiesRequestObject) (ListOpportunitiesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOrgAuctions(context.Context, ListOrgAuctionsRequestObject) (ListOrgAuctionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOrgPools(context.Context, ListOrgPoolsRequestObject) (ListOrgPoolsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOrgProcurement(context.Context, ListOrgProcurementRequestObject) (ListOrgProcurementResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOrgSuppliers(context.Context, ListOrgSuppliersRequestObject) (ListOrgSuppliersResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOrgTransactions(context.Context, ListOrgTransactionsRequestObject) (ListOrgTransactionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListPublicActivity(context.Context, ListPublicActivityRequestObject) (ListPublicActivityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListPublicListings(context.Context, ListPublicListingsRequestObject) (ListPublicListingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListRfqs(context.Context, ListRfqsRequestObject) (ListRfqsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) Login(context.Context, LoginRequestObject) (LoginResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) LoginWithGoogle(context.Context, LoginWithGoogleRequestObject) (LoginWithGoogleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) Logout(context.Context, LogoutRequestObject) (LogoutResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) MarkNotificationsRead(context.Context, MarkNotificationsReadRequestObject) (MarkNotificationsReadResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) MoveMmPipelineStage(context.Context, MoveMmPipelineStageRequestObject) (MoveMmPipelineStageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) OpenMmRound(context.Context, OpenMmRoundRequestObject) (OpenMmRoundResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) PlaceBid(context.Context, PlaceBidRequestObject) (PlaceBidResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) QualifyForAuction(context.Context, QualifyForAuctionRequestObject) (QualifyForAuctionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) Register(context.Context, RegisterRequestObject) (RegisterResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RemoveOrgMember(context.Context, RemoveOrgMemberRequestObject) (RemoveOrgMemberResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RequestOrgPoolMarket(context.Context, RequestOrgPoolMarketRequestObject) (RequestOrgPoolMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RequestOrgVerification(context.Context, RequestOrgVerificationRequestObject) (RequestOrgVerificationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RequestPhoneOtp(context.Context, RequestPhoneOtpRequestObject) (RequestPhoneOtpResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ResendVerificationEmail(context.Context, ResendVerificationEmailRequestObject) (ResendVerificationEmailResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ResetPassword(context.Context, ResetPasswordRequestObject) (ResetPasswordResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SaveMyBankAccount(context.Context, SaveMyBankAccountRequestObject) (SaveMyBankAccountResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SaveMyIdentity(context.Context, SaveMyIdentityRequestObject) (SaveMyIdentityResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SaveMyNotificationPrefs(context.Context, SaveMyNotificationPrefsRequestObject) (SaveMyNotificationPrefsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) Search(context.Context, SearchRequestObject) (SearchResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SendMessage(context.Context, SendMessageRequestObject) (SendMessageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SetMarketWatchPrice(context.Context, SetMarketWatchPriceRequestObject) (SetMarketWatchPriceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SetMmMarketStatus(context.Context, SetMmMarketStatusRequestObject) (SetMmMarketStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SettleMmRound(context.Context, SettleMmRoundRequestObject) (SettleMmRoundResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) StartConversation(context.Context, StartConversationRequestObject) (StartConversationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SubmitKtpVerification(context.Context, SubmitKtpVerificationRequestObject) (SubmitKtpVerificationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SubmitMyListingToMarket(context.Context, SubmitMyListingToMarketRequestObject) (SubmitMyListingToMarketResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SubmitQuote(context.Context, SubmitQuoteRequestObject) (SubmitQuoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateMmMarketRules(context.Context, UpdateMmMarketRulesRequestObject) (UpdateMmMarketRulesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateMyListing(context.Context, UpdateMyListingRequestObject) (UpdateMyListingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateOrgMember(context.Context, UpdateOrgMemberRequestObject) (UpdateOrgMemberResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateOrgProfile(context.Context, UpdateOrgProfileRequestObject) (UpdateOrgProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateOrgTeamSettings(context.Context, UpdateOrgTeamSettingsRequestObject) (UpdateOrgTeamSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UploadOrgDocument(context.Context, UploadOrgDocumentRequestObject) (UploadOrgDocumentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) VerifyEmail(context.Context, VerifyEmailRequestObject) (VerifyEmailResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) VerifyPhoneOtp(context.Context, VerifyPhoneOtpRequestObject) (VerifyPhoneOtpResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) WithdrawMyBid(context.Context, WithdrawMyBidRequestObject) (WithdrawMyBidResponseObject, error) {
	return nil, ErrNotImplemented
}
