// Command stubgen writes internal/api/unimplemented.gen.go: an Unimplemented type with every StrictServerInterface
// method returning ErrNotImplemented. The real server embeds it, so each operation answers 501 until a method with the
// same name is defined on the server (Go method promotion lets the real one win).
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/api/api.gen.go", nil, parser.SkipObjectResolution)
	if err != nil {
		fail(err)
	}
	var methods []*ast.Field
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "StrictServerInterface" {
			return true
		}
		methods = ts.Type.(*ast.InterfaceType).Methods.List
		return false
	})
	if len(methods) == 0 {
		fail(fmt.Errorf("StrictServerInterface not found"))
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Names[0].Name < methods[j].Names[0].Name })

	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/api/stubgen. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

// ErrNotImplemented is returned by every Unimplemented method; the server maps it to 501 not_implemented.
var ErrNotImplemented = errors.New("not implemented")

// Unimplemented answers every operation with ErrNotImplemented. Embed it and define the operations you implement.
type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}
`)
	for _, m := range methods {
		ft := m.Type.(*ast.FuncType)
		req := ft.Params.List[1].Type.(*ast.Ident).Name
		res := ft.Results.List[0].Type.(*ast.Ident).Name
		fmt.Fprintf(&b, "\nfunc (Unimplemented) %s(context.Context, %s) (%s, error) {\n\treturn nil, ErrNotImplemented\n}\n", m.Names[0].Name, req, res)
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("internal/api/unimplemented.gen.go", out, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("internal/api/unimplemented.gen.go: %d operations\n", len(methods))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "stubgen:", err)
	os.Exit(1)
}
