package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/api/api.gen.go", nil, parser.SkipObjectResolution)
	if err != nil {
		fail(err)
	}
	var methods []*ast.Field
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "StrictServerInterface" {
			return true
		}
		methods = ts.Type.(*ast.InterfaceType).Methods.List
		return false
	})
	if len(methods) == 0 {
		fail(fmt.Errorf("StrictServerInterface not found"))
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Names[0].Name < methods[j].Names[0].Name })

	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/api/stubgen. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

var ErrNotImplemented = errors.New("not implemented")

type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}
`)
	for _, m := range methods {
		ft := m.Type.(*ast.FuncType)
		req := ft.Params.List[1].Type.(*ast.Ident).Name
		res := ft.Results.List[0].Type.(*ast.Ident).Name
		fmt.Fprintf(&b, "\nfunc (Unimplemented) %s(context.Context, %s) (%s, error) {\n\treturn nil, ErrNotImplemented\n}\n", m.Names[0].Name, req, res)
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("internal/api/unimplemented.gen.go", out, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("internal/api/unimplemented.gen.go: %d operations\n", len(methods))
	if err := stripComments("internal/api/api.gen.go"); err != nil {
		fail(err)
	}
}

func keepComment(text string) bool {
	return strings.HasPrefix(text, "//go:") || strings.HasPrefix(text, "// Code generated ")
}

func stripComments(path string) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return err
	}
	var kept []*ast.CommentGroup
	for _, g := range f.Comments {
		var list []*ast.Comment
		for _, c := range g.List {
			if keepComment(c.Text) {
				list = append(list, c)
			}
		}
		if len(list) > 0 {
			kept = append(kept, &ast.CommentGroup{List: list})
		}
	}
	f.Comments, f.Doc = kept, nil
	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.Field:
			x.Doc, x.Comment = nil, nil
		case *ast.GenDecl:
			x.Doc = nil
		case *ast.FuncDecl:
			x.Doc = nil
		case *ast.ImportSpec:
			x.Doc, x.Comment = nil, nil
		case *ast.ValueSpec:
			x.Doc, x.Comment = nil, nil
		case *ast.TypeSpec:
			x.Doc, x.Comment = nil, nil
		}
		return true
	})
	var b bytes.Buffer
	if err := format.Node(&b, fset, f); err != nil {
		return err
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, out, 0o644)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "stubgen:", err)
	os.Exit(1)
}
