#!/usr/bin/env bash
# Regenerates docs/database-tables.md from the live schema (table comments, columns, FKs). Run after `make migrate`.
set -euo pipefail
. ./.env
psql_q() { docker exec -i ecopurnity-postgres-primary-1 psql -U ecopurnity -d ecopurnity -At -F $'\t' -c "$1"; }
{
  echo "# Tables"
  echo
  echo "Generated by \`scripts/db-doc.sh\` from the migrated schema. Design notes: [database.md](database.md)."
  echo
  echo "| Table | What a row is | Columns | References |"
  echo "| --- | --- | --- | --- |"
  psql_q "
    SELECT c.relname,
           coalesce(replace(obj_description(c.oid), '|', '/'), ''),
           (SELECT count(*) FROM pg_attribute a WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped),
           coalesce((SELECT string_agg(DISTINCT f.relname, ', ') FROM pg_constraint k JOIN pg_class f ON f.oid = k.confrelid
                     WHERE k.conrelid = c.oid AND k.contype = 'f' AND f.oid <> c.oid), '')
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relname <> 'goose_db_version'
    ORDER BY c.relname" | while IFS=$'\t' read -r t d n r; do echo "| \`$t\` | $d | $n | $r |"; done
} > docs/database-tables.md
echo "docs/database-tables.md: $(grep -c '^| `' docs/database-tables.md) tables"
